/**
 *  Disclaimer
 *  This project was created by Ryan Davern.
 *  Start Date: 30/03/2016.
 *  
 *  Copyright (C) 2017 Ryan Davern - All Rights Reserved.
 *  You may not use, distribute, monetize or modify this code under the terms of the Copyright Act 1994.
 *  You may use the compiled program, which can be downloaded at https://www.beatplaylist.com/. Any modified versions or versions uploaded to a different website is against TOS (https://www.beatplaylist.com/terms).
 *  
 *  For more information on the Copyright Act 1994, please visit http://www.legislation.govt.nz/act/public/1994/0143/latest/DLM345634.html.
 */

package com.beatplaylist.utilities.validation;

public class ValidateManager {

	public static boolean doesEmailPassValidation(String email) {
		char[] chars = email.toCharArray();
		for (char c : chars) {
			// Does the email contain any characters that aren't between A-Z, a-z, 0-9, @, ., - or an underscore, return false.
			if (!String.valueOf(c).matches("[\\w_.@-]"))
				return false;
		}
		return true;
	}

	public static boolean doesUsernamePassValidation(String email) {
		char[] chars = email.toCharArray();
		for (char c : chars) {
			// Does the username contain any characters that aren't between A-Z, a-z, 0-9 or an underscore, return false.
			if (!String.valueOf(c).matches("[\\w_]"))
				return false;
		}
		return true;
	}

	public static boolean doesCreditCardPass(String creditCard) {
		char[] chars = creditCard.toCharArray();
		for (char c : chars) {
			// Does the email contain any characters that aren't between A-Z, a-z, 0-9, @, ., - or an underscore, return false.
			if (!String.valueOf(c).matches("[0-9\\s]"))
				return false;
		}
		return true;
	}

	// Returns whether a string contains anything other than letters. E.g. Numbers
	public static boolean isAlphabetical(String value) {
		char[] chars = value.toCharArray();
		for (char c : chars) {
			if (!Character.isLetter(c))
				return false;
		}
		return true;
	}

	// Returns whether a string is numeric.
	public static boolean isNumeric(String value) {
		char[] chars = value.toCharArray();
		for (char c : chars) {
			if (!Character.isDigit(c))
				return false;
		}
		return true;
	}

	// Codes generated by BeatPlaylist contain letters, digits (numbers), and underscores.
	// Returns whether of not a string contains a value that isn't a letter, digit or underscore.
	public static boolean isValidCode(String value) {
		char[] chars = value.toCharArray();
		for (char c : chars) {
			if (!Character.isLetter(c) && !Character.isDigit(c) && !String.valueOf(c).equals("_"))
				return false;
		}
		return true;
	}
}