package com.beatplaylist.utilities.permission;

public enum PermissionName {

	LYRIC_VIEW, CREATE_PLAYLIST, LOAD_PLAYLIST, SYNC_PLAYLIST_TO_YOUTUBE, //
	CREATE_ACCOUNT, LOGIN, MAINTENANCE_MODE, WALLET_DISCONNECT, WALLET_CONFIRM_SYNC, //
	CLAIM_REWARD, CONNECT_TWITTER, CONNECT_YOUTUBE, CONNECT_INSTAGRAM, SAVE_YOUTUBE_PLAYLIST;
	
}
